languageCode = "zh-CN"
languageName = "简体中文"
languageDirection = "ltr"
weight = 2

title = "Ming Liu"
copyright = "&copy; 2026 Ming Liu"


[params]
  dateFormat = "2006年1月2日"

[params.author]
  name = "刘铭"
  image = "img/author1.png"
  headline = "东南大学 生物科学与医学工程学院"
  bio = "聚焦人工智能与生物医学工程的交叉领域。"
  links = [
    { email = "javascript:alert('220252564@seu.edu.cn')" },
    { github = "https://github.com/bbyg233" }
  ]