languageCode = "en-AU"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Ming Liu"
copyright = "&copy; 2026 Ming Liu"

[params]
  dateFormat = "2 January 2006"

[params.author]
  name = "Ming Liu"
  image = "img/author1.png"
  headline = "School of Biological Science and Medical Engineering, Southeast University"
  bio = "Focusing on the intersection of Artificial Intelligence and Biomedical Engineering."
  links = [
  { email = "mailto:220252564@seu.edu.cn" },
  { github = "https://github.com/bbyg233" }
]
